#include "digger_credits.h"

const char credits[] =
    "The Canadian\n"
    "studio \n"
    RED "Windmill\n"
    "Software" GREEN "\n"
    "lead programmer\n"
    RED "Rob Stealth" GREEN " and\n"
    "his teammates\n"
    RED "Ray Ewan" GREEN " and\n"
    RED "Bill Montgomery" GREEN "\n"
    "released \n"
    RED "Digger" GREEN " in " BLUE "1983" GREEN "\n"
    "for " RED "IBM PC" GREEN ".\n"
    "\n"
    "In " BLUE "2026" RED " Digger" GREEN "\n"
    "was converted\n"
    "to run on the\n"
    "Soviet computer\n"
    RED "\xE2\xEB 0010-01" GREEN ".\n";
